version: '3.8'
services:
  backend:
    build: .
    volumes:
    - .:/app
    ports:
    - 8000:8000
    depends_on:
      - db

  db:
    image: mysql:5.7.35
    restart: always
    environment:
      MYSQL_DATABASE: ambassador
      MYSQL_USER: quan
      MYSQL_PASSWORD: quan
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - .dbdata:/var/lib/mysql
    ports:
      - 3309:3306


