# Generated by Django 3.1.7 on 2021-10-14 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='products',
        ),
        migrations.AddField(
            model_name='link',
            name='products',
            field=models.ManyToManyField(to='core.Product'),
        ),
    ]
