# Generated by Django 3.1.7 on 2021-11-19 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20211014_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='products',
            field=models.ManyToManyField(related_name='product', to='core.Product'),
        ),
    ]
